1 '''
 2 Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 3
 4 Triangle        T_n=n(n+1)/2        1, 3, 6, 10, 15, ...
 5 Pentagonal      P_n=n(3n-1)/2       1, 5, 12, 22, 35, ...
 6 Hexagonal       H_n=n(2n-1)         1, 6, 15, 28, 45, ...
 7
 8 It can be verified that T_285 = P_165 = H_143 = 40755.
 9
10 Find the next triangle number that is also pentagonal and hexagonal.
11 '''
12
13 MAX = 100000
14 triangle = [ n * (  n + 1) / 2 for n in xrange(0, MAX) ]
15 pentagon = [ n * (3*n - 1) / 2 for n in xrange(0, MAX) ]
16 hexagon  = [ n * (2*n - 1)     for n in xrange(0, MAX) ]
17 pentagon_dict = dict.fromkeys(pentagon, 1)
18 hexagon_dict  = dict.fromkeys(hexagon, 1)
19
20 for t in xrange(286, MAX):
21     v = triangle[t]
22     if pentagon_dict.has_key(v) and hexagon_dict.has_key(v):
23         print v
24         break