1 '''
 2 How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100
 3 '''
 4
 5 terms = {}
 6 count = 0
 7 for a in xrange(2,101):
 8     for b in xrange(2,101):
 9         c = pow(a,b)
10         if not terms.get(c, 0):
11             terms[c] = 1
12             count = count + 1
13
14 print count